export const CART_ADD_ITEM = 'CART_ADD_ITEM'
export const CART_CREATE_ITEM = 'CART_CREATE_ITEM'

export const CART_CLEAR_ITEMS = 'CART_RESET'
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM'
export const CART_ADD_ITEM_FAIL ='CART_ADD_ITEM_FAIL'
export const CART_SAVE_SHIPPING_ADDRESS = 'CART_SAVE_SHIPPING_ADDRESS'
export const CART_SAVE_PAYMENT_METHOD = 'CART_SAVE_PAYMENT_METHOD'
export const CART_ADD_PAYMENT_METHOD = 'CART_ADD_PAYMENT_METHOD'
export const SHIPPING_DETAILS_FAIL="SHIPPING_DETAILS_FAIL"
export const SHIPPING_DETAILS_REQUEST="SHIPPING_DETAILS_SUCCESS"
export const SHIPPING_DETAILS_SUCCESS="SHIPPING_DETAILS_SUCCESS"